app/hotel_management/urls.py
from django.urls import path, reverse_lazy
from hotel.views import register_user, dismiss_user, assign_shift, view_orders, create_order, change_order_status, home, view_shifts, user_list, fire_user
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.auth.forms import AuthenticationForm
urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', register_user, name='register_user'),
    path('dismiss/<int:user_id>/', dismiss_user, name='dismiss_user'),
    path('assign_shift/', assign_shift, name='assign_shift'),
    path('view_shifts/', view_shifts, name='view_shifts'),
    path('orders/', view_orders, name='view_orders'),
    path('orders/create/', create_order, name='create_order'),
    path('orders/<int:order_id>/status/<str:status>/', change_order_status, name='change_order_status'),
    path('', home, name='home'),
    path('logout/', auth_views.LogoutView.as_view(
        next_page=reverse_lazy('login')
    ), name='logout'),
    # path('login/', auth_views.LoginView.as_view(authentication_form=AuthenticationForm, redirect_authenticated_user=True), name='login'),
    path('login/', auth_views.LoginView.as_view(authentication_form=AuthenticationForm, redirect_authenticated_user=True), name='login'),

    path('user_list/', user_list, name='user_list'),
    path('fire_user/<int:user_id>/', fire_user, name='fire_user'),
    # path('orders/<int:orderid>/preparation_status/', order_preparation_status_update, name='order_preparation_status_update'),
    # path('orders/<int:orderid>/payment_status/', order_payment_status_update, name='order_payment_status_update'),
]

app/hotel/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

# Модель пользователя
class User(AbstractUser):
    # Возможные роли пользователя
    ROLE_CHOICES = (
        ('менеджер', 'Менеджер'),
        ('сотрудник_обслуживания_номеров', 'Сотрудник обслуживания номеров'),
        ('сотрудник_предоставления_услуг', 'Сотрудник предоставления услуг отеля'),
    )
    # Возможные статусы пользователя
    STATUS_CHOICES = (
        ('работает', 'Работает'),
        ('уволен', 'Уволен'),
    )
    role = models.CharField(max_length=50, choices=ROLE_CHOICES)  # Роль пользователя
    first_name = models.CharField(max_length=30)  # Имя пользователя
    last_name = models.CharField(max_length=30)  # Фамилия пользователя
    father_name = models.CharField(max_length=30, default='-')  # Отчество пользователя
    status = models.CharField(max_length=30, choices=STATUS_CHOICES, default='работает')  # Статус пользователя

# Модель заказа
class Order(models.Model):
    # Возможные статусы заказа
    STATUS_CHOICES = (
        ('в_процессе', 'В процессе'),
        ('готов', 'Готов'),
    )
    # Возможные статусы оплаты заказа
    PAYMENT_STATUS_CHOICES = (
        ('принят', 'Принят'),
        ('оплачен', 'Оплачен'),
    )
    created_by = models.ForeignKey(User, related_name='orders', on_delete=models.CASCADE)  # Создатель заказа
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='preparing')  # Статус заказа
    created_at = models.DateTimeField(auto_now_add=True)  # Дата создания заказа
    updated_at = models.DateTimeField(auto_now=True)  # Дата последнего обновления заказа
    details = models.TextField()  # Детали заказа
    room_num = models.CharField(max_length=7, default=1)  # Номер комнаты
    amount_clients = models.IntegerField(default=1)  # Количество клиентов
    payment_status = models.CharField(max_length=20, choices=PAYMENT_STATUS_CHOICES, default='pending')  # Статус оплаты

# Модель смены
class Shift(models.Model):
    user = models.ForeignKey(User, related_name='shifts', on_delete=models.CASCADE)  # Пользователь, которому назначена смена
    start_time = models.DateTimeField()  # Время начала смены
    end_time = models.DateTimeField()  # Время окончания смены

    def __str__(self):
        # Возвращает строковое представление смены
        return f"{self.user.username}: {self.start_time} - {self.end_time}"

app/hotel/forms.py
# hotel/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import User, Order, Shift

# Форма для регистрации пользователя
class UserRegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'password1', 'password2', 'role']  # Поля формы
        labels = {
            'username': 'Логин',
            'password1': 'Пароль',
            'password2': 'Подтверждение пароля',
            'role': 'Должность',
        }

# Форма для создания/редактирования заказа
class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['details', 'status', 'payment_status', 'amount_clients', 'room_num']  # Поля формы
        labels = {
            'details': 'Детали заказа',
            'status': 'Статус заказа',
            'payment_status': 'Статус оплаты',
            'amount_clients': 'Количество клиентов',
            'room_num': 'Номер комнаты',
        }

# Форма для назначения смен
class ShiftAssignmentForm(forms.ModelForm):
    class Meta:
        model = Shift
        fields = ['user', 'start_time', 'end_time']  # Поля формы
        labels = {
            'user': 'Сотрудник',
            'start_time': 'Начало смены',
            'end_time': 'Конец смены',
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Фильтрация пользователей по роли и статусу для выбора в форме
        self.fields['user'].queryset = User.objects.filter(role__in=['сотрудник_обслуживания_номеров', 'сотрудник_предоставления_услуг'], status='работает')

# Расширенная форма регистрации пользователя
class UserRegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'password1', 'password2', 'role', 'first_name', 'last_name', 'father_name', 'status']  # Поля формы
        labels = {
            'username': 'Имя пользователя',
            'password1': 'Пароль',
            'password2': 'Подтверждение пароля',
            'role': 'Должность',
            'first_name': 'Имя',
            'last_name': 'Фамилия',
            'father_name': 'Отчество',
            'status': 'Статус',
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['status'].initial = 'active'  # Установка начального значения статуса

# Форма для изменения статуса оплаты заказа
class OrderStatusPaymentForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['payment_status']  # Поле формы
        read_only_fields = ['room_num', 'amount_clients', 'hotel_services', 'status']  # Поля только для чтения

# Форма для изменения статуса заказа
class OrderStatusOrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['status']  # Поле формы
        read_only_fields = ['room_num', 'amount_clients', 'hotel_services', 'order_status']  # Поля только для чтения

app/hotel/views.py
from django.contrib.auth import login, authenticate
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from .forms import UserRegistrationForm, OrderForm, ShiftAssignmentForm
from .models import User, Order, Shift

@login_required
def register_user(request):
    # Проверка, что пользователь является менеджером
    if request.user.role  not in ['manager','менеджер']:
        return redirect('home')
    
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            form.save()  # Сохранение нового пользователя
            return redirect('home')
    else:
        form = UserRegistrationForm()  # Создание пустой формы
    
    # Отображение страницы регистрации пользователя
    return render(request, 'hotel/register_user.html', {'form': form})

@login_required
def dismiss_user(request, user_id):
    # Проверка, что пользователь является менеджером
    if request.user.role  not in ['manager','менеджер']:
        return redirect('home')
    
    user = get_object_or_404(User, id=user_id)
    user.status = 'dismissed'  # Изменение статуса пользователя на "уволен"
    user.save()
    return redirect('register_user')  # Перенаправление на страницу регистрации пользователей

@login_required
def assign_shift(request):
    # Проверка, что пользователь является менеджером
    if request.user.role  not in ['manager','менеджер']:
        return redirect('home')
    


    if request.method == 'POST':
        form = ShiftAssignmentForm(request.POST)
        if form.is_valid():
            form.save()  # Сохранение новой смены
            return redirect('home')
    else:
        form = ShiftAssignmentForm()  # Создание пустой формы
    
    # Отображение страницы назначения смен
    return render(request, 'hotel/assign_shift.html', {'form': form})

@login_required
def view_shifts(request):
    # Проверка, что пользователь является менеджером
    if request.user.role not in ['manager','менеджер']:
        return redirect('home')
    

    shifts = Shift.objects.all()  # Получение всех смен
    # Отображение страницы просмотра смен
    return render(request, 'hotel/view_shifts.html', {'shifts': shifts})

@login_required
def view_orders(request):
    # Проверка, что пользователь имеет необходимую роль
    if request.user.role not in ['manager','менеджер',  'сотрудник_предоставления_услуг', 'сотрудник_обслуживания_номеров']:
        return redirect('home')
    
    orders = Order.objects.all()  # Получение всех заказов
    # Отображение страницы просмотра заказов
    return render(request, 'hotel/view_orders.html', {'orders': orders})


@login_required
def update_order(request, order_id):
    order = get_object_or_404(Order, id=order_id)
    if request.method == 'POST':
        # Здесь должна быть логика для обновления статуса заказа
        form = OrderForm(request.POST, instance=order)
        if form.is_valid():
            form.save()
            return redirect('view_orders')
    else:
        form = OrderForm(instance=order)
    return render(request, 'hotel/update_order.html', {'form': form, 'order': order})

@login_required
def create_order(request):
    # Проверка, что пользователь имеет необходимую роль
    if request.user.role not in ['manager','менеджер', 'сотрудник_обслуживания_номеров']: 
        return redirect('home')
    
    if request.method == 'POST':
        form = OrderForm(request.POST)
        if form.is_valid():
            order = form.save(commit=False)
            order.created_by = request.user  # Установка пользователя, создавшего заказ
            order.save()
            return redirect('home')
    else:
        form = OrderForm()  # Создание пустой формы
    
    # Отображение страницы создания заказа
    return render(request, 'hotel/create_order.html', {'form': form})
@login_required
def change_order_status(request, order_id):
    order = get_object_or_404(Order, id=order_id)
    
    # Проверка, что пользователь имеет необходимую роль
    if request.user.role not in ['сотрудник_обслуживания_номеров', 'сотрудник_предоставления_услуг']:
        return redirect('home')
    
    if request.method == 'POST':
        new_status = request.POST.get('status')
        # Проверка допустимости изменения статуса заказа в зависимости от роли пользователя
        if (request.user.role == 'сотрудник_обслуживания_номеров' and new_status in ['Принят', 'Оплачен']) or (request.user.role == 'сотрудник_предоставления_услуг' and new_status in ['В процессе', 'Готов']):
            order.status = new_status
            order.save()
            return redirect('view_orders')
    
    # Если метод не POST или статус не допустим, возвращаемся на страницу заказов
    return redirect('view_orders')

@login_required
def home(request):
    # Отображение домашней страницы
    return render(request, 'hotel/home.html')

@login_required
def user_list(request):
    users = User.objects.all()  # Получение всех пользователей
    # Отображение страницы со списком пользователей
    return render(request, 'hotel/user_list.html', {'users': users})

@login_required
def fire_user(request, user_id):
    user = get_object_or_404(User, id=user_id)
    # Логика для изменения статуса пользователя на "уволен"
    user.status = 'уволен'
    user.save()
    return redirect('user_list')  # Перенаправление на страницу со списком пользователей

app/hotel/templates/hotel/assign_shift.html
{% extends 'base_generic.html' %}
{% block content %}
  <h2>Создать смену</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Сохранить</button>
  </form>
{% endblock %}

app/hotel/templates/hotel/create_order.html
{% extends 'base_generic.html' %}
{% block content %}
  <h2>Создать заказ</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Создать</button>
  </form>
{% endblock %}

app/hotel/templates/hotel/home.html
{% extends 'base_generic.html' %}
{% block content %}
  
  
{% endblock %}

app/hotel/templates/hotel/register_user.html
{% extends 'base_generic.html' %}

{% block content %}


<div class="registration-container">
    <h2>Регистрация пользователя</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Зарегистрировать</button>
    </form>
</div>
{% endblock %}

app/hotel/templates/hotel/update_order.html
{% extends "base.html" %}
 
{% block content %}
    <h2>Изменение статуса</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Изменить</button>
    </form>
{% endblock %}

app/hotel/templates/hotel/update_order_status.html
{% extends "base.html" %}

{% block title %}Update Order Payment Status{% endblock %}
 
{% block content %}
  <h2>Update Payment Status for Order {{ order.orderid }}</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Update Status</button>
  </form>
  <a href="{% url 'main' %}">Back to Order Details</a>
{% endblock %}

app/hotel/templates/hotel/user_list.html
{% extends 'base_generic.html' %}
{% block content %}

  
<div class="user-list-container">
    <h2>Список пользователей</h2>
    <table>
        <thead>
            <tr>
                <th>Имя пользователя</th>
                <th>Имя</th>
                <th>Фамилия</th>
                <th>Отчество</th>
                <th>Должность</th>
                <th>Статус</th>
                <th>Действие</th>
            </tr>
        </thead>
        <tbody>
            {% for user in users %}
                <tr>
                    <td>{{ user.username }}</td>
                    <td>{{ user.first_name }}</td>
                    <td>{{ user.last_name }}</td>
                    <td>{{ user.father_name }}</td>
                    <td>{{ user.get_role_display }}</td>
                    <td>{{ user.get_status_display }}</td>
                    <td>
                        {% if user.status != 'уволен' %}
                            <form method="post" action="{% url 'fire_user' user.id %}">
                                {% csrf_token %}
                                <button type="submit">Уволить</button>
                            </form>
                        {% else %}
                            Уволен
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

app/hotel/templates/hotel/view_orders.html
{% extends 'base_generic.html' %}
{% block content %}
  <h2>Заказы</h2>  
  <div class="container">
    <div class="row">
      {% for order in orders %}
        <div class="col-md-4 mb-4">
          <div class="card">
            <div class="card-body">
              <h5 class="card-title">{{ order.details }}</h5>
              {% if user.role == 'manager' %}
              <form method="post" action="{% url 'view_orders' %}">
                {% csrf_token %}
                <input type="hidden" name="order_id" value="{{ order.id }}">
                  <div class="form-group">
                    <label for="payment_status_{{ order.id }}">Статус оплаты:</label>
                    <select name="payment_status" id="payment_status_{{ order.id }}" class="form-control">
                      <option value="Принят"{% if order.payment_status == 'Принят' %} selected{% endif %}>Принят</option>
                      <option value="Оплачен"{% if order.payment_status == 'Оплачен' %} selected{% endif %}>Оплачен</option>
                    </select>
                  </div>
                  <div class="form-group">
                    <label for="status_{{ order.id }}">Статус заказа:</label>
                    <select name="status" id="status_{{ order.id }}" class="form-control">
                      <option value="В процессе"{% if order.status == 'В процессе' %} selected{% endif %}>В процессе</option>
                      <option value="Готов"{% if order.status == 'Готов' %} selected{% endif %}>Готов</option>
                    </select>
                  </div>
                  <button type="submit" class="btn btn-primary">Обновить</button>
                </form>
              {% elif user.role == 'менеджер' %}
              <form method="post" action="{% url 'view_orders' %}">
                {% csrf_token %}
                <input type="hidden" name="order_id" value="{{ order.id }}">
                  <div class="form-group">
                    <label for="payment_status_{{ order.id }}">Статус оплаты:</label>
                    <select name="payment_status" id="payment_status_{{ order.id }}" class="form-control">
                      <option value="Принят"{% if order.payment_status == 'Принят' %} selected{% endif %}>Принят</option>
                      <option value="Оплачен"{% if order.payment_status == 'Оплачен' %} selected{% endif %}>Оплачен</option>
                    </select>
                  </div>
                  <div class="form-group">
                    <label for="status_{{ order.id }}">Статус заказа:</label>
                    <select name="status" id="status_{{ order.id }}" class="form-control">
                      <option value="В процессе"{% if order.status == 'В процессе' %} selected{% endif %}>В процессе</option>
                      <option value="Готов"{% if order.status == 'Готов' %} selected{% endif %}>Готов</option>
                    </select>
                  </div>
                  <button type="submit" class="btn btn-primary">Обновить</button>
                </form>
              {% elif user.role == 'сотрудник_обслуживания_номеров' %}
              <form method="post" action="{% url 'view_orders' %}">
                {% csrf_token %}
                <input type="hidden" name="order_id" value="{{ order.id }}">
                <div class="form-group">
                  <label for="payment_status_{{ order.id }}">Статус оплаты:</label>
                  <select name="payment_status" id="payment_status_{{ order.id }}" class="form-control">
                    <option value="Принят"{% if order.payment_status == 'Принят' %} selected{% endif %}>Принят</option>
                    <option value="Оплачен"{% if order.payment_status == 'Оплачен' %} selected{% endif %}>Оплачен</option>
                  </select>
                </div>
                <button type="submit" class="btn btn-primary">Обновить</button>
              </form>
              {% elif user.role == 'сотрудник_предоставления_услуг' %}
              <form method="post" action="{% url 'view_orders' %}">
                {% csrf_token %}
                <input type="hidden" name="order_id" value="{{ order.id }}">
              <div class="form-group">
                <label for="status_{{ order.id }}">Статус заказа:</label>
                <select name="status" id="status_{{ order.id }}" class="form-control">
                  <option value="В процессе"{% if order.status == 'В процессе' %} selected{% endif %}>В процессе</option>
                  <option value="Готов"{% if order.status == 'Готов' %} selected{% endif %}>Готов</option>
                </select>
              </div>
              <button type="submit" class="btn btn-primary">Обновить</button>
            </form>
              {% endif %}
            </div>
          </div>
        </div>
      {% endfor %}
    </div>
  </div>
{% endblock %}

app/hotel/templates/hotel/view_shifts.html
{% extends 'base_generic.html' %}
{% block content %}
  <h2>Смены</h2> 
  <div class="container">
    <div class="row">
      {% for shift in shifts %}
        <div class="col-md-4 mb-4">
          <div class="card">
            <div class="card-body">
              <h5 class="card-title">{{ shift.user.username }}</h5>
              <p class="card-text">{{ shift.start_time }} - {{ shift.end_time }}</p>
            </div>
          </div>
        </div>
      {% endfor %}
    </div>
  </div>
{% endblock %}